### ISSUE TITLE
This library appears as "not compatible" in "Library Manager" of Processing IDE (3.0.2)

### ISSUE THREAD

**Issue by q2dg** [jagracar/grafica#3]
Can you confirm it?
Thanks!

**Comment by jagracar** [comment]
Hi @q2dg 
Sorry for taking so long to answer. I was trying several things to make the lib compatible and at the end it seems that I had to write the Processing libs maintainer to update one of their configuration scripts.

Anyway, the problem is fixed now and the lib is no longer grey in Processing 3 (tested in 3.1.1).

Cheers and thank you for using the library!

**Comment by q2dg** [comment]
Thanks to you!!
I close the issue, then.
